[package]
name = "spmv"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
nalgebra = "0.32.2"
sprs = "0.11.0"
nalgebra-sparse = "0.9.0"
num_cpus = "1.0"
